Repository sparklemotion/nokogiri, pull requests merged in 2020-02, with the labels that each got.

#1859 [#1482] remove library paths from version output
  CHANGELOG.md
  ext/nokogiri/extconf.rb
  ext/nokogiri/nokogiri.c
  lib/nokogiri/version.rb
Labels: state/pr-will-merge

#1571 Linux binary gems
  .cross_rubies
  Gemfile
  Rakefile
  build_all
  ext/nokogiri/extconf.rb
Labels: meta/discussion

#2000 support "keyword attributes" via new methods on Nokogiri::XML::Node
  lib/nokogiri/xml/node.rb
  lib/nokogiri/xml/searchable.rb
  test/xml/node/test_attribute_methods.rb
  test/xml/test_node.rb
Labels: state/in-progress
