Repository sparklemotion/nokogiri, pull requests merged in 2021-12, with the labels that each got.

#2391 update source links to https where possible
  ext/nokogiri/extconf.rb
Labels: needs/more-info

#2379 Add tests to cover line numbering edge cases with JRuby
  CHANGELOG.md
  ext/java/nokogiri/XmlNode.java
  ext/nokogiri/xml_node.c
  test/helper.rb
  test/xml/test_node.rb
Labels: platform/jruby

#2332 native gem: aarch64-linux support
  .cross_rubies
  CHANGELOG.md
  rakelib/extensions.rake
  scripts/test-gem-build
Labels: packaging/native-gem
