Repository sparklemotion/nokogiri, pull requests merged in 2021-08, with the labels that each got.

#2299 fix BSD support for libgumbo
  .github/workflows/ci.yml
  Vagrantfile
  gumbo-parser/src/Makefile
Labels: platform/openbsd

#2294 feat(cruby): patch libxml2 to handle abruptly-closed HTML comments
  CHANGELOG.md
  patches/libxml2/0008-htmlParseComment-handle-abruptly-closed-comments.patch
  test/html4/test_comments.rb
Labels: topic/HTML5, state/pr-will-merge, upstream/libxml2

#2296 Resolve potential NPE in SchemaResourceResolver
  ext/java/nokogiri/XmlSchema.java
  test/html4/test_node.rb
  test/xml/test_schema.rb
Labels: platform/jruby
