Repository sparklemotion/nokogiri, pull requests merged in 2022-07, with the labels that each got.

#2579 Fix compaction on nodes
  ext/nokogiri/extconf.rb
  ext/nokogiri/gumbo.c
  ext/nokogiri/nokogiri.h
  ext/nokogiri/xml_attr.c
  ext/nokogiri/xml_attribute_decl.c
  ext/nokogiri/xml_cdata.c
  ext/nokogiri/xml_document.c
  ext/nokogiri/xml_dtd.c
  ext/nokogiri/xml_element_decl.c
  ext/nokogiri/xml_entity_decl.c
  ext/nokogiri/xml_node.c
  ext/nokogiri/xml_node_set.c
  ext/nokogiri/xml_schema.c
  ext/nokogiri/xml_text.c
  ext/nokogiri/xml_xpath_context.c
  suppressions/nokogiri_ruby.supp
  test/test_compaction.rb
Labels: topic/memory

#2588 Fix compaction on nodes (backport to v1.13.x)
  .github/workflows/gem-install.yml
  ext/nokogiri/extconf.rb
  ext/nokogiri/gumbo.c
  ext/nokogiri/nokogiri.h
  ext/nokogiri/xml_attr.c
  ext/nokogiri/xml_attribute_decl.c
  ext/nokogiri/xml_cdata.c
  ext/nokogiri/xml_document.c
  ext/nokogiri/xml_dtd.c
  ext/nokogiri/xml_element_decl.c
  ext/nokogiri/xml_entity_decl.c
  ext/nokogiri/xml_node.c
  ext/nokogiri/xml_node_set.c
  ext/nokogiri/xml_schema.c
  ext/nokogiri/xml_text.c
  ext/nokogiri/xml_xpath_context.c
  nokogiri.gemspec
  suppressions/nokogiri_ruby.supp
  test/test_compaction.rb
Labels: topic/memory, backport

#2591 ci: ensure pipeline uses the RCD IMAGE_VERSION for containers
  .github/workflows/gem-install.yml
  nokogiri.gemspec
  scripts/test-gem-build
Labels: topic/ci, packaging/native-gem

#2592 dep: remove ruby-maven workaround from 433850c
  misc/ruby-maven-3.3.12.gem
  rakelib/extensions.rake
  scripts/test-gem-build
Labels: packaging/native-gem

#2596 Implement HTML 5 serialization in C
  ext/nokogiri/xml_node.c
  lib/nokogiri/html5.rb
  lib/nokogiri/html5/node.rb
  test/html5/test_serialize.rb
Labels: topic/HTML5, topic/performance

#2601 ci: update vmactions/freebsd-vm job config
  .github/workflows/ci.yml
Labels: topic/ci

#2603 ci: suppress memleak reports from gc stack_chunk_alloc
  suppressions/nokogiri_ruby.supp
Labels: topic/ci
