Repository sparklemotion/nokogiri, pull requests merged in 2022-08, with the labels that each got.

#2618 ci: fix development dependency breakage
  .github/workflows/ci.yml
  .github/workflows/gem-install.yml
  .github/workflows/generate-ci-images.yml
  .github/workflows/upstream.yml
  nokogiri.gemspec
  rakelib/docker.rake
Labels: topic/ci

#2616 dep(dev): update ruby_memcheck to v1.0.3
  nokogiri.gemspec
  suppressions/nokogiri_ruby.supp
Labels: topic/ci, topic/memory

#2624 ci: upstream libxml2 fixed conditional html comments
  test/html4/test_comments.rb
Labels: upstream/libxml2

#2628 dep: update libxslt to v1.1.36
  CHANGELOG.md
  dependencies.yml
  ext/nokogiri/extconf.rb
Labels: upstream/libxslt

#2633 dep: move dev dependencies into Gemfile
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  nokogiri.gemspec
  rakelib/rubocop.rake
Labels: topic/ci

#2637 ci: workaround recent bundler release bug
  scripts/test-gem-install
Labels: topic/ci

#2638 dep: upgrade to libxml 2.10.1 and libiconv 1.17
  CHANGELOG.md
  dependencies.yml
Labels: upstream/libxml2, dependencies

#1942 Do not override encoding set during initialisation
  lib/nokogiri/xml/sax/parser.rb
  test/xml/sax/test_parser.rb
Labels: topic/encoding, state/pr-under-review

#2641 test: pending test for JRuby schema validation issue
  test/xml/test_schema.rb
Labels: platform/jruby, needs/fix-for-failing-test
