Repository sparklemotion/nokogiri, pull requests merged in 2024-12, with the labels that each got.

#3350 fix: escape foreign style tag content when serializing HTML5 (v1.15.x)
  CHANGELOG.md
  ext/nokogiri/xml_node.c
  test/html5/test_serialize.rb
Labels: backport

#3349 fix: escape foreign style tag content when serializing HTML5 (v1.16.x)
  CHANGELOG.md
  ext/nokogiri/xml_node.c
  test/html5/test_serialize.rb
Labels: backport

#3342 XML::RelaxNG argument forwarding
  CONTRIBUTING.md
  ext/nokogiri/xml_relax_ng.c
  lib/nokogiri/xml/relax_ng.rb
Labels: event/hackday2024

#3329 Update html5.rb forwarding params syntax
  lib/nokogiri/html5.rb
Labels: event/hackday2024

#3333 Nokogiri::XML::Schema.read_memory() support keyword arguments
  ext/nokogiri/xml_relax_ng.c
  ext/nokogiri/xml_schema.c
  lib/nokogiri/xml/relax_ng.rb
  lib/nokogiri/xml/schema.rb
  test/xml/test_relax_ng.rb
  test/xml/test_schema.rb
Labels: event/hackday2024

#3326 Implement XML::Reader.new with keyword args and forward Reader() to it
  ext/nokogiri/xml_reader.c
  lib/nokogiri/xml.rb
  lib/nokogiri/xml/reader.rb
  test/xml/test_reader_encoding.rb
Labels: event/hackday2024

#3334 Updates HTML5::Document.parse with keyword arguments;
  lib/nokogiri/html5.rb
  lib/nokogiri/html5/document.rb
  test/html5/test_api.rb
  test/html5/test_nokogumbo.rb
Labels: event/hackday2024

#3332 Nokogiri::XML() and Nokogiri::XML.parse() support argument forwarding
  lib/nokogiri/xml.rb
  test/xml/test_document.rb
  test/xml/test_document_encoding.rb
  test/xml/test_node_encoding.rb
Labels: event/hackday2024

#3356 Nokogiri::XSLT() uses parameter forwarding
  lib/nokogiri/xslt.rb
Labels: event/hackday2024

#3364 fix: Node#dup adds the new node to the document's node cache (backport to v1.17.x)
  ext/nokogiri/xml_node.c
  test/xml/test_document_fragment.rb
  test/xml/test_node.rb
Labels: backport

#3372 fix(jruby): XML::DocumentFragment.dup to another document
  ext/java/nokogiri/XmlNode.java
  test/xml/test_node.rb
Labels: platform/jruby

#3373 fix(jruby): XML::DocumentFragment.dup to another document (v1.17.x)
  ext/java/nokogiri/XmlNode.java
  test/xml/test_node.rb
Labels: platform/jruby, backport

#3389 perf: use libxml2 patch for faster xpath context init
  CHANGELOG.md
  ext/nokogiri/xml_xpath_context.c
  lib/nokogiri/xml/searchable.rb
  lib/nokogiri/xml/xpath_context.rb
  patches/libxml2/0019-xpath-Use-separate-static-hash-table-for-standard-fu.patch
  test/xml/test_xpath.rb
  test/xml/test_xpath_context.rb
Labels: topic/performance

#3395 fix: SAX::ParserContext keeps a reference to the input
  ext/nokogiri/xml_sax_parser_context.c
  test/test_memory_usage.rb
Labels: topic/memory

#3396 fix: SAX::ParserContext keeps a reference to the input (backport of #3395 to v1.18.x)
  CHANGELOG.md
  ext/nokogiri/xml_sax_parser_context.c
  test/test_memory_usage.rb
Labels: backport
